services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.9@sha256:bc9fa8e1462fffe3d8d4255fc62af478602641f4c0e5f4875fea8563d1189837
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /srv/media/family/movies:/media/family/movies:ro
      - /srv/media/family/music:/media/family/music:ro
      - /srv/media/jellyfin/movies:/media/movies:ro
      - /srv/media/jellyfin/shows:/media/shows:ro
      - /srv/media/jellyfin/music:/media/music:ro
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      # - type: bind
      #   source: /path/to/fonts
      #   target: /usr/local/share/fonts/custom
      #   read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
