services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:1.15.5@sha256:add80c37eb2cc6d1e9622f3590ba4ee72c94a765c51a3b5e1afc485a4ec89135
    container_name: immich-public-proxy
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      PUBLIC_BASE_URL: https://immich-share.timonrieger.de
      IMMICH_URL: http://beelink:2283
    healthcheck:
      test: curl -s http://localhost:3000/share/healthcheck -o /dev/null || exit 1
      start_period: 10s
      timeout: 5s
    volumes:
      - ./config.json:/app/config.json:ro
