services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:1.15.0@sha256:fed53746338583e56e468462d0eb746f8f39ad4827147e5b99535611e634fec3
    container_name: immich-public-proxy
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      PUBLIC_BASE_URL: https://immich-share.timonrieger.de
      IMMICH_URL: http://beelink:2283
    healthcheck:
      test: curl -s http://localhost:3000/share/healthcheck -o /dev/null || exit 1
      start_period: 10s
      timeout: 5s
    volumes:
      - ./config.json:/app/config.json:ro
