services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:3.0.2@sha256:96b8667fd0df62693c79ddce6ade78d9a70d84f301c860c6f22b6f65acf73262
    container_name: immich-public-proxy
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      PUBLIC_BASE_URL: https://immpub.timonrieger.de
      IMMICH_URL: http://beelink:2283
    healthcheck:
      test: curl -s http://localhost:3000/share/healthcheck -o /dev/null || exit 1
      start_period: 10s
      timeout: 5s
    volumes:
      - ./config.json:/app/config.json:ro
