name: immichframe
services:
  immichframe:
    container_name: immichframe
    image: ghcr.io/immichframe/immichframe:v1.0.33.0@sha256:1680d2f63a89fa0db6e5a7c5c497bed27a47f314efe18e1f11cff1dea1910f57
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      TZ: "Europe/Zurich"
