name: immichframe
services:
  immichframe:
    container_name: immichframe
    image: ghcr.io/immichframe/immichframe:v1.0.32.0@sha256:a0b54ee307d5746cd59518bd3ff60d80bf133b5dbe3202585f8c788d9ce3f2a8
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      TZ: "Europe/Zurich"
