name: immichframe
services:
  immichframe:
    container_name: immichframe
    image: ghcr.io/immichframe/immichframe:v1.0.35.0@sha256:6ff37b0b1f94822e6ed006315f7b517e300d6a4c26881a6701261b3de4b69de9
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      TZ: "Europe/Zurich"
