services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.16.0@sha256:74496aed2c5055e3b7b6c4e1bb9b4f16b1f566601582b258a10bae851f19ac24
    container_name: mealie
    restart: unless-stopped
    user: ${PUID}:${PGID}
    ports:
        - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./data:/app/data/
    env_file:
      - .env
