services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.17.0@sha256:d570139f1891346131d02f8e4d1853100ae4846474958ca6c68cfe1648058467
    container_name: mealie
    restart: unless-stopped
    user: ${PUID}:${PGID}
    ports:
        - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./data:/app/data/
    env_file:
      - .env
