services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.19.0@sha256:116555e24d66c5026db1d7b96a942222e7bd400db5c57a0896d3deb17540a815
    container_name: mealie
    restart: unless-stopped
    user: ${PUID}:${PGID}
    ports:
        - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./data:/app/data/
    env_file:
      - .env
